### ISSUE TITLE
iphone 4s(iOS 7.1.2 or 7.1.1) call gcm.register() crash

### ISSUE THREAD

**Issue by redsparrowWang** [myflashlab/GCM-ANE#25] opened 2016-08-30 04:34 UTC
Hello , i got a problem need help, please

I had use this ANE in Flash Builder(AS3) to make app.
and when use gcm.register(); will be crash at iphone 4s(iOS 7.1.2 or 7.1.1), 
tried 2 same device, got same result, 
but work fine at iphone 5(ios 9.3.2) and iphone6(iOS 9.3.2)

Requirements wrote Android 10 or higher and iOS 6.1 or higher, 
Could i make sure this ANE work fine at iphone 4s(iOS 7.1.2 or 7.1.1)? 
and did it have any solution ?

**// here is my source**
```
private function initNotification():void {
	Gcm.isSandbox = true;
	var gcm:Gcm = new Gcm("myProductNumber", "myProductNumber");
	CONFIG::ANDROID {
		if (gcm.isSupported() == false) {
			return;
		}
	};
	gcm.addEventListener(GcmEvent.REGISTERED, onRegIdReceived);
	gcm.addEventListener(GcmEvent.UNREGISTERED, onUnregistered);
	gcm.addEventListener(GcmEvent.ERROR, onError);
	gcm.addEventListener(GcmEvent.MESSAGE, onMessage);
	CONFIG::DEBUG{trace("GCM ANE os = " + gcm.os);};
	CONFIG::DEBUG{trace("GCM ANE getOSVersion = " + gcm.getOSVersion());};
	CONFIG::DEBUG{trace("GCM ANE regId = " + gcm.getRegId);};
	gcm.register(); // <- here will be crash at iphone 4s(iOS 7.1.2 or 7.1.1), tried 2 same device, got same result, work fine at iphone 5(ios 9.3.2) and iphone6(iOS 9.3.2)
}
```

**// here is my app's xml setting**
```
<iPhone>
	<InfoAdditions><![CDATA[
		<key>MinimumOSVersion</key> <string>6.1</string>
		<key>UIApplicationExitsOnSuspend</key> <true/>
		<key>UIViewControllerBasedStatusBarAppearance</key> <false/>
		<key>UIStatusBarStyle</key> <string>UIStatusBarStyleLightContent</string>
		<key>CFBundleURLTypes</key>
		<array> 
			<dict> 
				<key>CFBundleURLSchemes</key> 
					<array> 
						<string>myPackagename</string> 
					</array>
					<key>CFBundleURLName</key> 
				<string>myPackagename</string>
			</dict> 
		</array>
		<key>UIPrerenderedIcon</key> <true/> 
		<key>NSAppTransportSecurity</key>
		<dict>
			<key>NSAllowsArbitraryLoads</key>
			<true/>
		</dict>

		<key>UIDeviceFamily</key>
		<array>
			<string>1</string>
			<!-- iPadはサポート対象外にする -->
			<string>2</string>
		</array>
		<key>UIBackgroundModes</key>
		<array>
			<string>fetch</string>
			<string>remote-notification</string>
		</array>
		<key>UIRequiresPersistentWiFi</key> <string>NO</string>
		<key>GCM_SENDER_ID</key> <string>mySenderID</string>
		<key>PLIST_VERSION</key> <string>1</string>
		<key>BUNDLE_ID</key> <string>myPackageName</string>
		<key>IS_ADS_ENABLED</key> <false/>
		<key>IS_ANALYTICS_ENABLED</key> <false/>
		<key>IS_APPINVITE_ENABLED</key> <false/>
		<key>IS_GCM_ENABLED</key> <true/>
		<key>IS_SIGNIN_ENABLED</key> <false/>
	]]></InfoAdditions>
	<requestedDisplayResolution>high</requestedDisplayResolution>
	<Entitlements>
		<![CDATA[
			<key>keychain-access-groups</key>
			<array>
				<string> myKey.*</string>
			</array>
			<key>get-task-allow</key> <true/>
			<key>application-identifier</key> <string> myKey.myPackageName</string>
			<key>com.apple.developer.team-identifier</key> <string>myKey</string>
			<key>aps-environment</key> <string>development</string>
		]]>
	</Entitlements>
</iPhone>
<extensions>
		<extensionID>com.myflashlab.air.extensions.dependency.androidSupport</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.basement</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.iid</extensionID>
		<extensionID>com.myflashlab.air.extensions.dependency.googlePlayServices.gcm</extensionID>
		<extensionID>com.myflashlab.air.extensions.gcm</extensionID>
</extensions>
```

**// here is infomation part of xcode device console**
Aug 30 12:57:30 iPhone4sDNPHD352DTDG myPackagename[293] <Warning>: GCM ANE os = ios
Aug 30 12:57:30 iPhone4sDNPHD352DTDG myPackagename[293] <Warning>: GCM ANE getOSVersion = 7.1.1
Aug 30 12:57:30 iPhone4sDNPHD352DTDG myPackagename[293] <Warning>: GCM ANE regId = 
Aug 30 12:57:30 iPhone4sDNPHD352DTDG myPackagename[293] <Error>: -[CTApplication registerForRemoteNotifications]: unrecognized selector sent to instance 0x17642de0
Aug 30 12:57:30 iPhone4sDNPHD352DTDG myPackagename[293] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CTApplication registerForRemoteNotifications]: unrecognized selector sent to instance 0x17642de0'
	*** First throw call stack:
	(0x2ee26fd3 0x3969fccf 0x2ee2a967 0x2ee29253 0x2ed787b8 0x685115 0x6839f9 0x4a71c0 0x5fdf07 0x5fd871 0x5fd609 0x5c2c2d 0x5c2c2d 0x5c2c2d 0x5c2c2d 0x5c2c2d 0x5c2c2d 0xacdec 0xab970 0x2e70ec 0x5fdf07 0x5fd871 0x5fd609 0x5c2c2d 0x5c2c2d 0x5a7071 0x59d4b1 0x5fdf07 0x5fd871 0x5fd609 0x5c2c2d 0x5c2c2d 0xacdec 0xac3d8 0xac3a0 0xaebd0 0x306348 0x5fdf07 0x5fd871 0x5fd609 0x5c2c2d 0x39c814 0x2009f8 0x1fc7e8 0x201098 0x18ef4c 0x18fa8c 0xbf154 0x3130edf3 0x3130eb9d 0x340db75d 0x2fb11451 0x2ede6ef9 0x2edf1ab7 0x2edf1a53 0x2edf0227 0x2ed5af0f 0x2ed5acf3 0x33cb3663 0x316a616d 0x1bb128 0x39bacab7)
Aug 30 12:57:30 iPhone4sDNPHD352DTDG ReportCrash[296] <Notice>: ReportCrash acting against PID 293

**// here is infomation part of crash report**
Incident Identifier: F0DF28C2-0646-43BD-9616-32F0DDC2B862
CrashReporter Key:   a0ceb0279d8d6a1159fd2edb83ec29a1ca8f7468
Hardware Model:      iPhone4,1
Process:             myPackagename [293]
Path:                /var/mobile/Applications/99649463-DC03-4754-97C8-F17DB18C1131/myPackagename.app/myPackagename
Identifier:          myPackageName
Version:             1.7.6 (1.7.6)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2016-08-30 12:57:30.141 +0900
OS Version:          iOS 7.1.1 (11D201)
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

**Comment by redsparrowWang** [comment] 2016-08-30 05:30
add some info 
[Application registerForRemoteNotifications]: unrecognized selector sent to instance 0x17642de0]
it's look like got call method failed in ANE at iphone4(iOS7.1.1 or iOS7.1.2)
and i find this link may be help
http://stackoverflow.com/questions/24485681/registerforremotenotifications-method-not-being-called-properly
sorry i don't know this ANE's detail, so please confirm it.

**Comment by myflashlab** [comment] 2016-08-31 06:05
Thanks for reporting this issue. we will send you a new version a.s.a.p so you can test and see if the new version has fixed the problem...?

**Comment by redsparrowWang** [comment] 2016-08-31 06:23
Hi, 

Thanks response my issue, and very glad to test new version
please send new version to this mail, and i will be test it as soon as possible, thank you.  

Best Regards

**Comment by myflashlab** [comment] 2016-09-07 09:22
Please try this new build V5.0.1 (with demo dialog. make sure you are closing the dialog prior to calling other ANE methods.)
[gcmV5.0.1.zip](https://github.com/myflashlab/GCM-ANE/files/458734/gcmV5.0.1.zip)

Let me know if the problem is now fixed?

**Comment by redsparrowWang** [comment] 2016-09-07 09:29
Hi,
Thank you very much, I got it, and will be test it as soon as possible.

**Comment by redsparrowWang** [comment] 2016-09-09 05:47
Hi,

I'm glad to post a good message, i had tested new version and it work very well, good job.
this is test list, pls confirm it.

|GCM-ANE Compatibility check|
|platform|version detail|model|result|
|Android |Android4.0.4 |SAMSUNG GLAXY ISW11SC |ok |
|Android |Android4.1.2 |SHARP AQUOS PHONE SBM203SH ok |
|Android |Android5.0.2 |SONY SOV31 |ok |
|Android |Android5.1.1 |ASUS Nexus7 |ok  |
|Android |Andorid6.0.1 |LG Nexus5x |ok |
|iOS |iOS7.1.1 |iPhone4s |ok |
|iOS |iOS7.1.2 |iPhone4s |ok |
|iOS |iOS8.3 |iPhone6 Plus |ok |
|iOS |iOS9.3.2 |iPhone5c |ok |
|iOS |iOS9.3.2 |iPhone6 |ok |

Could i ask another question at here?

1. I want to know parameter detail (iOS and Android), where can be get it ?
Is’t all in this demo (http://www.myflashlabs.com/showcase/AIR_EXTENSIONS/GCM/demoV4/) 
or just a part of parameter, need i purchase it will be get full version.

2. this ANE work very well on android, Is’t possible to show notification on system status bar when my app is running (not closed, on background or showing multi task )?

**Comment by myflashlab** [comment] 2016-09-13 11:22
V5.0.1 is now released with the bug fixed. And as far as the parameter details, they are all explained in asdoc here http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/gcm/package-detail.html

**Closed by myflashlab** 2016-09-13 11:22 UTC
Labels: bug

**Comment by redsparrowWang** [comment] 2016-09-14 03:02
Thanks, I got it.
